import {
  CustomerMaster,
  JobMaster,
  EmployeeMaster,
  MachineMaster,
  ProcessMaster,
  AdminMaster,
  JobOrder,
  InventoryItem,
  StockTransaction,
  PurchaseOrder,
  Quotation,
  MonthlyExpenses,
  NotificationItem,
  ProductionAuditLog,
} from "./types";

export const INITIAL_CUSTOMERS: CustomerMaster[] = [
  {
    id: "cust-1",
    code: "D02",
    companyName: "Cipla Healthcare Ltd.",
    contactPerson: "Dr. Arvind Shinde",
    mobile: "+91 98220 11452",
    email: "procurement@cipla-miraj.com",
    location: "MIDC Kupwad, Sangli, MH - 416436",
    gstin: "27AAACC1206D1ZM",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Regular", "Pharma", "High Volume"],
    isLocked: false,
  },
  {
    id: "cust-2",
    code: "S01",
    companyName: "Sun Wellness Organics",
    contactPerson: "Vikram Deshmukh",
    mobile: "+91 98901 44520",
    email: "vikram@sunwellness.in",
    location: "Industrial Estate, Miraj, MH - 416410",
    gstin: "27AABCS9912E1ZQ",
    isGstRegistered: true,
    creditTerms: "15 Days Credit",
    tags: ["Regular", "FMCG", "Export Quality"],
    isLocked: false,
  },
  {
    id: "cust-3",
    code: "P04",
    companyName: "Patil Agro Chemicals & Seeds",
    contactPerson: "Suresh Patil",
    mobile: "+91 94230 88910",
    email: "packaging@patilagro.com",
    location: "Market Yard, Sangli, MH - 416416",
    gstin: "27AAAFP4412K1Z9",
    isGstRegistered: true,
    creditTerms: "Immediate / Advance",
    tags: ["Agro", "Heavy Substrate", "Seasonal"],
    isLocked: false,
  },
  {
    id: "cust-4",
    code: "Z09",
    companyName: "Zydus Natural Formulations",
    contactPerson: "Sneha Kulkarni",
    mobile: "+91 97654 33211",
    email: "sneha.k@zydusnatural.com",
    location: "MIDC Shirol, Kolhapur, MH - 416103",
    gstin: "27AABCZ3301L1ZT",
    isGstRegistered: true,
    creditTerms: "45 Days Credit",
    tags: ["Regular", "Met-Pet", "Premium Finishing"],
    isLocked: false,
  },
  {
    id: "cust-5",
    code: "M05",
    companyName: "Mahalaxmi Sweets & Bakers",
    contactPerson: "Amol Chougule",
    mobile: "+91 98224 77610",
    email: "info@mahalaxmisweets.com",
    location: "Vishrambag, Sangli, MH - 416415",
    gstin: "27AAGCM8819J1Z1",
    isGstRegistered: true,
    creditTerms: "Cash On Delivery",
    tags: ["Food Packaging", "Met-Pet Gold", "Crash Lock"],
    isLocked: false,
  },
];

export const INITIAL_JOBS: JobMaster[] = [
  {
    id: "job-1",
    jobCode: "JC-MED-5001",
    productName: "Paracetamol 500mg Embossed Drip-off Mono Carton",
    customerId: "cust-1",
    customerCode: "D02",
    customerName: "Cipla Healthcare Ltd.",
    sheetSize: '28" × 40" (710 × 1020 mm)',
    sheetLengthInches: 40,
    sheetWidthInches: 28,
    boardType: "FBB Cyber XL Pac",
    boardGsm: 300,
    colors: "CMYK + Pantone 072C Reflex Blue + Spot Drip-off",
    numColors: 5,
    sides: 1,
    ups: 12,
    dieCode: "DIE-MED-042",
    artworkUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Thermal Gloss Lamination", "Spot UV Drip-off", "Die Punching", "Straight Line Pasting"],
  },
  {
    id: "job-2",
    jobCode: "JC-FMCG-2004",
    productName: "Organic Green Tea 25s Lock Bottom Carton",
    customerId: "cust-2",
    customerCode: "S01",
    customerName: "Sun Wellness Organics",
    sheetSize: '25" × 36" (635 × 915 mm)',
    sheetLengthInches: 36,
    sheetWidthInches: 25,
    boardType: "Virgin Kraft Backed Ivory Board",
    boardGsm: 280,
    colors: "CMYK + Eco Matte Aqueous Varnish",
    numColors: 4,
    sides: 1,
    ups: 8,
    dieCode: "DIE-FMCG-018",
    artworkUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Aqueous Matte Coating", "Die Punching & Embossing", "Crash Lock Bottom Pasting"],
  },
  {
    id: "job-3",
    jobCode: "JC-AGRO-7011",
    productName: "Bio-Fertilizer 1kg Heavy Duty Corrugated Laminated Mono Box",
    customerId: "cust-3",
    customerCode: "P04",
    customerName: "Patil Agro Chemicals & Seeds",
    sheetSize: '30" × 40" (760 × 1020 mm)',
    sheetLengthInches: 40,
    sheetWidthInches: 30,
    boardType: "Duplex Grey Back Coated",
    boardGsm: 350,
    colors: "CMYK + High Gloss UV Varnish",
    numColors: 4,
    sides: 1,
    ups: 6,
    dieCode: "DIE-AGRO-091",
    artworkUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Thermal Gloss Lamination", "Die Punching", "Heavy Flute Pasting"],
  },
  {
    id: "job-4",
    jobCode: "JC-MET-8802",
    productName: "Ayurvedic Hair Vitalizer Met-Pet Gold Foil Drip-Off Box",
    customerId: "cust-4",
    customerCode: "Z09",
    customerName: "Zydus Natural Formulations",
    sheetSize: '22" × 32" (560 × 810 mm)',
    sheetLengthInches: 32,
    sheetWidthInches: 22,
    boardType: "Met-Pet Gold Polyester Laminated FBB",
    boardGsm: 320,
    colors: "White Base + CMYK + Spot Gloss UV Drip-off",
    numColors: 6,
    sides: 1,
    ups: 10,
    dieCode: "DIE-LUX-033",
    artworkUrl: "https://images.unsplash.com/photo-1608248597359-0091398bb9ff?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["UV Inks Curing", "Drip-off Texture", "Precision Die Cut", "Side Seam Pasting"],
  },
  {
    id: "job-5",
    jobCode: "JC-SWEET-302",
    productName: "Premium Kaju Katli 500g Golden Rigid Style Folding Box",
    customerId: "cust-5",
    customerCode: "M05",
    customerName: "Mahalaxmi Sweets & Bakers",
    sheetSize: '28" × 40" (710 × 1020 mm)',
    sheetLengthInches: 40,
    sheetWidthInches: 28,
    boardType: "Food Grade SBS Virgin Board",
    boardGsm: 350,
    colors: "CMYK + Gold Foil Stamping + Velvet Soft Touch Lamination",
    numColors: 5,
    sides: 2,
    ups: 4,
    dieCode: "DIE-SWT-104",
    artworkUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Velvet Soft-Touch Lamination", "Hot Foil Stamping", "Embossing", "Die Punching", "Manual Box Assembly"],
  },
];

export const INITIAL_EMPLOYEES: EmployeeMaster[] = [
  { id: "emp-1", staffId: "EMP-101", name: "Ramesh Pawar", department: "Press", phone: "+91 94220 12345", shift: "Morning (8AM-4PM)", status: "Active" },
  { id: "emp-2", staffId: "EMP-102", name: "Sunil Kadam", department: "Pre-Press", phone: "+91 98500 54321", shift: "Morning (8AM-4PM)", status: "Active" },
  { id: "emp-3", staffId: "EMP-103", name: "Santosh Mane", department: "Post-Press", phone: "+91 98810 67890", shift: "Evening (4PM-12AM)", status: "Active" },
  { id: "emp-4", staffId: "EMP-104", name: "Pooja Deshpande", department: "Quality", phone: "+91 97300 11223", shift: "General", status: "Active" },
  { id: "emp-5", staffId: "EMP-105", name: "Vikas More", department: "Dispatch", phone: "+91 99220 99887", shift: "General", status: "Active" },
];

export const INITIAL_MACHINES: MachineMaster[] = [
  { id: "mac-1", machineId: "M-01", name: "Heidelberg Speedmaster CD 102 (6-Color + Coater)", type: "Offset Press", speedImpPerHour: 11000, hourlyRate: 2200, currentJobCode: "JC-MED-5001", status: "Running" },
  { id: "mac-2", machineId: "M-02", name: "Heidelberg SM 74 (4-Color)", type: "Offset Press", speedImpPerHour: 8500, hourlyRate: 1500, currentJobCode: "JC-FMCG-2004", status: "Running" },
  { id: "mac-3", machineId: "M-03", name: "Bobst Novacut 106 E Automatic Die Cutter", type: "Die Cutter", speedImpPerHour: 7500, hourlyRate: 1200, currentJobCode: "JC-AGRO-7011", status: "Running" },
  { id: "mac-4", machineId: "M-04", name: "DGM Smartfold 1100 Auto Folder Gluer", type: "Folder Gluer", speedImpPerHour: 18000, hourlyRate: 950, currentJobCode: "JC-MET-8802", status: "Idle" },
  { id: "mac-5", machineId: "M-05", name: "Screen PlateRite 8600 Thermal CTP", type: "CTP Processor", speedImpPerHour: 22, hourlyRate: 800, status: "Idle" },
];

export const INITIAL_PROCESSES: ProcessMaster[] = [
  { id: "prc-1", code: "P-CTP", name: "Thermal CTP Plate Exposure & Baking", unitRate: 450, rateUnit: "per Plate", category: "Pre-Press", machineType: "CTP Processor", setupTimeMin: 15 },
  { id: "prc-2", code: "P-OFF", name: "Offset 4-Color Printing Impression", unitRate: 180, rateUnit: "per 1000 Imp", category: "Press", machineType: "Offset Press", setupTimeMin: 30 },
  { id: "prc-3", code: "P-LAM-T", name: "Thermal Gloss / Matte BOPP Lamination", unitRate: 1.40, rateUnit: "per Sheet", category: "Coating & Lamination", machineType: "Laminator", setupTimeMin: 20 },
  { id: "prc-4", code: "P-UV-DRIP", name: "Inline UV Drip-off Structure Coating", unitRate: 2.20, rateUnit: "per Sheet", category: "Coating & Lamination", machineType: "Coater", setupTimeMin: 25 },
  { id: "prc-5", code: "P-DIE", name: "Automatic Die Punching & Creasing", unitRate: 0.95, rateUnit: "per Sheet", category: "Finishing & Pasting", machineType: "Die Cutter", setupTimeMin: 40 },
  { id: "prc-6", code: "P-PASTE-L", name: "Linear Side-Seam Auto Pasting", unitRate: 0.22, rateUnit: "per Carton", category: "Finishing & Pasting", machineType: "Folder Gluer", setupTimeMin: 25 },
  { id: "prc-7", code: "P-PASTE-CR", name: "Crash Lock Bottom Auto Pasting", unitRate: 0.45, rateUnit: "per Carton", category: "Finishing & Pasting", machineType: "Folder Gluer", setupTimeMin: 45 },
];

export const INITIAL_ADMINS: AdminMaster[] = [
  { id: "adm-1", username: "admin_om", name: "Om Upadhye", email: "om@perfectprinters.com", role: "ADMIN", status: "Active", lastLogin: "Today, 19:42" },
  { id: "adm-2", username: "sales_mahesh", name: "Mahesh Joshi", email: "mahesh@perfectprinters.com", role: "SALES", status: "Active", lastLogin: "Today, 17:15" },
  { id: "adm-3", username: "prod_sawant", name: "Anand Sawant", email: "anand@perfectprinters.com", role: "PRODUCTION", status: "Active", lastLogin: "Today, 18:30" },
  { id: "adm-4", username: "acc_shinde", name: "Ketan Shinde", email: "accounts@perfectprinters.com", role: "ACCOUNTS", status: "Active", lastLogin: "Yesterday, 16:50" },
];

export const INITIAL_JOB_ORDERS: JobOrder[] = [
  {
    id: "ORD-2026-0842",
    jobId: "job-1",
    jobCode: "JC-MED-5001",
    jobName: "Paracetamol 500mg Embossed Drip-off Mono Carton",
    customerId: "cust-1",
    customerName: "Cipla Healthcare Ltd.",
    customerCode: "D02",
    quantity: 50000,
    ups: 12,
    totalSheetsRequired: 4420,
    makereadySheets: 250,
    sheetSize: '28" × 40"',
    boardType: "FBB Cyber XL Pac",
    boardGsm: 300,
    colors: "CMYK + Pantone 072C",
    numColors: 5,
    status: "Press",
    progressPercent: 60,
    orderDate: "16 Aug 2026",
    dueDate: "24 Aug 2026",
    instructions: "High gloss drip-off texture required on Cipla logo. Strict cleanroom packaging.",
    artworkUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    assignedMachine: "Heidelberg CD 102",
    assignedOperator: "Ramesh Pawar",
  },
  {
    id: "ORD-2026-0841",
    jobId: "job-2",
    jobCode: "JC-FMCG-2004",
    jobName: "Organic Green Tea 25s Lock Bottom Carton",
    customerId: "cust-2",
    customerName: "Sun Wellness Organics",
    customerCode: "S01",
    quantity: 25000,
    ups: 8,
    totalSheetsRequired: 3325,
    makereadySheets: 200,
    sheetSize: '25" × 36"',
    boardType: "Virgin Kraft Backed Ivory Board",
    boardGsm: 280,
    colors: "CMYK + Aqueous Matte",
    numColors: 4,
    status: "Post-Press",
    progressPercent: 80,
    orderDate: "14 Aug 2026",
    dueDate: "22 Aug 2026",
    instructions: "Crash lock bottom test report needed before palletization.",
    artworkUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop",
    assignedMachine: "DGM Smartfold Gluer",
    assignedOperator: "Santosh Mane",
  },
  {
    id: "ORD-2026-0840",
    jobId: "job-3",
    jobCode: "JC-AGRO-7011",
    jobName: "Bio-Fertilizer 1kg Heavy Duty Outer Box",
    customerId: "cust-3",
    customerName: "Patil Agro Chemicals & Seeds",
    customerCode: "P04",
    quantity: 15000,
    ups: 6,
    totalSheetsRequired: 2650,
    makereadySheets: 150,
    sheetSize: '30" × 40"',
    boardType: "Duplex Grey Back Coated",
    boardGsm: 350,
    colors: "CMYK + High Gloss UV",
    numColors: 4,
    status: "Sheet Allocation",
    progressPercent: 40,
    orderDate: "18 Aug 2026",
    dueDate: "28 Aug 2026",
    instructions: "Verify moisture content of 350 GSM board before cutting.",
    artworkUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "ORD-2026-0839",
    jobId: "job-4",
    jobCode: "JC-MET-8802",
    jobName: "Ayurvedic Hair Vitalizer Met-Pet Gold Foil Drip-Off Box",
    customerId: "cust-4",
    customerName: "Zydus Natural Formulations",
    customerCode: "Z09",
    quantity: 30000,
    ups: 10,
    totalSheetsRequired: 3250,
    makereadySheets: 250,
    sheetSize: '22" × 32"',
    boardType: "Met-Pet Gold Polyester Laminated FBB",
    boardGsm: 320,
    colors: "White Base + CMYK + Drip-off",
    numColors: 6,
    status: "Pre-Press",
    progressPercent: 25,
    orderDate: "19 Aug 2026",
    dueDate: "30 Aug 2026",
    instructions: "Customer color proof approved via email on 18th Aug.",
    artworkUrl: "https://images.unsplash.com/photo-1608248597359-0091398bb9ff?q=80&w=600&auto=format&fit=crop",
    assignedMachine: "Screen PlateRite CTP",
    assignedOperator: "Sunil Kadam",
  },
  {
    id: "ORD-2026-0838",
    jobId: "job-5",
    jobCode: "JC-SWEET-302",
    jobName: "Premium Kaju Katli 500g Golden Rigid Folding Box",
    customerId: "cust-5",
    customerName: "Mahalaxmi Sweets & Bakers",
    customerCode: "M05",
    quantity: 10000,
    ups: 4,
    totalSheetsRequired: 2650,
    makereadySheets: 150,
    sheetSize: '28" × 40"',
    boardType: "Food Grade SBS Virgin Board",
    boardGsm: 350,
    colors: "CMYK + Gold Foil",
    numColors: 5,
    status: "Pending",
    progressPercent: 10,
    orderDate: "19 Aug 2026",
    dueDate: "02 Sep 2026",
    instructions: "Awaiting board delivery from ITC Bhadrachalam dealer.",
    artworkUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "ORD-2026-0835",
    jobId: "job-1",
    jobCode: "JC-MED-5001",
    jobName: "Paracetamol 500mg (Batch July Export)",
    customerId: "cust-1",
    customerName: "Cipla Healthcare Ltd.",
    customerCode: "D02",
    quantity: 100000,
    ups: 12,
    totalSheetsRequired: 8600,
    makereadySheets: 260,
    sheetSize: '28" × 40"',
    boardType: "FBB Cyber XL Pac",
    boardGsm: 300,
    colors: "CMYK + Spot Blue",
    numColors: 5,
    status: "Completed",
    progressPercent: 100,
    orderDate: "02 Aug 2026",
    dueDate: "12 Aug 2026",
    dispatchDate: "11 Aug 2026",
    challanNo: "DC-2026-0418",
    invoiceNo: "INV-2026-1190",
  },
  {
    id: "ORD-2026-0834",
    jobId: "job-2",
    jobCode: "JC-FMCG-2004",
    jobName: "Organic Green Tea (Monsoon Packaging)",
    customerId: "cust-2",
    customerName: "Sun Wellness Organics",
    customerCode: "S01",
    quantity: 40000,
    ups: 8,
    totalSheetsRequired: 5200,
    makereadySheets: 200,
    sheetSize: '25" × 36"',
    boardType: "Virgin Kraft Backed Ivory Board",
    boardGsm: 280,
    colors: "CMYK + Aqueous Matte",
    numColors: 4,
    status: "Completed",
    progressPercent: 100,
    orderDate: "28 Jul 2026",
    dueDate: "08 Aug 2026",
    dispatchDate: "07 Aug 2026",
    challanNo: "DC-2026-0410",
    invoiceNo: "INV-2026-1175",
  },
  {
    id: "ORD-2026-0830",
    jobId: "job-3",
    jobCode: "JC-AGRO-7011",
    jobName: "Bio-Fertilizer 1kg Carton (Spec Rev C)",
    customerId: "cust-3",
    customerName: "Patil Agro Chemicals & Seeds",
    customerCode: "P04",
    quantity: 20000,
    ups: 6,
    totalSheetsRequired: 3500,
    makereadySheets: 160,
    sheetSize: '30" × 40"',
    boardType: "Duplex Grey Back Coated",
    boardGsm: 350,
    colors: "CMYK",
    numColors: 4,
    status: "On Hold",
    progressPercent: 40,
    orderDate: "05 Aug 2026",
    dueDate: "20 Aug 2026",
    holdReason: "Client requested barcode & ingredient artwork correction on front panel.",
  },
  {
    id: "ORD-2026-0828",
    jobId: "job-4",
    jobCode: "JC-MET-8802",
    jobName: "Ayurvedic Hair Vitalizer (Test Batch)",
    customerId: "cust-4",
    customerName: "Zydus Natural Formulations",
    customerCode: "Z09",
    quantity: 5000,
    ups: 10,
    totalSheetsRequired: 700,
    makereadySheets: 200,
    sheetSize: '22" × 32"',
    boardType: "Met-Pet Gold",
    boardGsm: 320,
    colors: "White + CMYK",
    numColors: 5,
    status: "Cancelled",
    progressPercent: 10,
    orderDate: "20 Jul 2026",
    dueDate: "30 Jul 2026",
    cancelReason: "Client changed formulation bottle size; revised die punch needed.",
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: "inv-1", sku: "BRD-FBB-300", name: "ITC Cyber XL Pac FBB 300 GSM (28x40 in)", category: "Paper & Board", stockType: "Own Stock", quantity: 18500, unit: "Sheets", reorderLevel: 5000, costPerUnit: 18.5, totalValue: 342250, location: "Bay A - Stack 12", lastUpdated: "18 Aug 2026" },
  { id: "inv-2", sku: "BRD-DUP-350", name: "Emami Super White Duplex Grey Back 350 GSM (30x40 in)", category: "Paper & Board", stockType: "Own Stock", quantity: 9200, unit: "Sheets", reorderLevel: 3000, costPerUnit: 22.0, totalValue: 202400, location: "Bay A - Stack 05", lastUpdated: "17 Aug 2026" },
  { id: "inv-3", sku: "BRD-MET-320", name: "Met-Pet Gold Laminated FBB Board 320 GSM (22x32 in)", category: "Paper & Board", stockType: "Client Stock", clientName: "Zydus Natural Formulations", quantity: 4500, unit: "Sheets", reorderLevel: 1000, costPerUnit: 29.5, totalValue: 132750, location: "Bay C - Client Staging", lastUpdated: "19 Aug 2026" },
  { id: "inv-4", sku: "INK-CMYK-SET", name: "Hubergroup Premium Sheetfed Offset Ink Set (CMYK)", category: "Inks & Varnishes", stockType: "Own Stock", quantity: 240, unit: "Kg", reorderLevel: 50, costPerUnit: 480, totalValue: 115200, location: "Ink Room - Cabinet 1", lastUpdated: "16 Aug 2026" },
  { id: "inv-5", sku: "INK-PAN-072C", name: "Pantone 072C Reflex Blue Spot Ink", category: "Inks & Varnishes", stockType: "Own Stock", quantity: 35, unit: "Kg", reorderLevel: 10, costPerUnit: 720, totalValue: 25200, location: "Ink Room - Special", lastUpdated: "15 Aug 2026" },
  { id: "inv-6", sku: "FILM-BOPP-15U", name: "Thermal Gloss BOPP Film 15 Micron (710mm Roll)", category: "Lamination Film", stockType: "Own Stock", quantity: 18, unit: "Rolls", reorderLevel: 5, costPerUnit: 3400, totalValue: 61200, location: "Lamination Store", lastUpdated: "12 Aug 2026" },
  { id: "inv-7", sku: "ADH-PAST-WTR", name: "Pidilite Fast Setting Side Seam Adhesive", category: "Adhesives & Gum", stockType: "Own Stock", quantity: 420, unit: "Kg", reorderLevel: 100, costPerUnit: 145, totalValue: 60900, location: "Chemical Store", lastUpdated: "14 Aug 2026" },
  { id: "inv-8", sku: "COAT-UV-DRIP", name: "Hi-Tech UV Drip-off Gloss Varnish & Primer Kit", category: "UV & Aqueous Coatings", stockType: "Own Stock", quantity: 85, unit: "Kg", reorderLevel: 25, costPerUnit: 680, totalValue: 57800, location: "UV Mixing Room", lastUpdated: "17 Aug 2026" },
  { id: "inv-9", sku: "PLT-CTP-THERM", name: "Kodak Electra XD Thermal CTP Plates (770x1030 mm)", category: "Chemicals & Plates", stockType: "Own Stock", quantity: 140, unit: "Plates", reorderLevel: 40, costPerUnit: 380, totalValue: 53200, location: "CTP Dark Room", lastUpdated: "19 Aug 2026" },
];

export const INITIAL_TRANSACTIONS: StockTransaction[] = [
  { id: "tx-1", itemId: "inv-1", sku: "BRD-FBB-300", itemName: "ITC Cyber XL Pac FBB 300 GSM", type: "Stock In", quantity: 10000, unit: "Sheets", date: "16 Aug 2026", referenceNo: "PO-2026-0308", authorizedBy: "Om Upadhye", notes: "GRN-2026-091 verified from ITC dealer" },
  { id: "tx-2", itemId: "inv-1", sku: "BRD-FBB-300", itemName: "ITC Cyber XL Pac FBB 300 GSM", type: "Material Out (Job Issuance)", quantity: 4420, unit: "Sheets", date: "16 Aug 2026", referenceNo: "ORD-2026-0842", jobCode: "JC-MED-5001", authorizedBy: "Anand Sawant", notes: "Issued for Cipla Paracetamol 50k run" },
  { id: "tx-3", itemId: "inv-4", sku: "INK-CMYK-SET", itemName: "Hubergroup Offset CMYK Inks", type: "Material Out (Job Issuance)", quantity: 35, unit: "Kg", date: "17 Aug 2026", referenceNo: "ORD-2026-0842", jobCode: "JC-MED-5001", authorizedBy: "Ramesh Pawar" },
  { id: "tx-4", itemId: "inv-8", sku: "COAT-UV-DRIP", itemName: "UV Drip-off Gloss Varnish Kit", type: "Material Out (Job Issuance)", quantity: 15, unit: "Kg", date: "17 Aug 2026", referenceNo: "ORD-2026-0842", jobCode: "JC-MED-5001", authorizedBy: "Ramesh Pawar" },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-1",
    poNumber: "PO-2026-0312",
    supplierName: "Paper Trade Corporation (ITC Authorized)",
    supplierGstin: "27AAACP9910D1ZL",
    supplierAddress: "Industrial Area, Kolhapur, MH - 416001",
    poDate: "18 Aug 2026",
    deliveryDate: "23 Aug 2026",
    gstRate: 18,
    lineItems: [
      { id: "pli-1", itemType: "FBB Paperboard", description: "ITC Cyber XL Pac 300 GSM 28x40 inches", quantity: 15000, unit: "Sheets", rate: 18.50, amount: 277500 },
      { id: "pli-2", itemType: "Duplex Board", description: "Emami Super White Duplex 350 GSM 30x40 inches", quantity: 8000, unit: "Sheets", rate: 22.00, amount: 176000 },
    ],
    subtotal: 453500,
    gstAmount: 81630,
    grandTotal: 535130,
    terms: "1. 30 Days credit from date of invoice.\n2. Moisture content must be within 6-7%.\n3. Defective sheets subject to immediate debit note.",
    status: "Approved",
  },
  {
    id: "po-2",
    poNumber: "PO-2026-0311",
    supplierName: "Hubergroup India Private Limited",
    supplierGstin: "27AAACH0112F1ZK",
    supplierAddress: "Rabale MIDC, Navi Mumbai, MH - 400701",
    poDate: "15 Aug 2026",
    deliveryDate: "20 Aug 2026",
    gstRate: 18,
    lineItems: [
      { id: "pli-3", itemType: "Offset Inks", description: "Process Cyan, Magenta, Yellow, Black (50kg each)", quantity: 200, unit: "Kg", rate: 480, amount: 96000 },
      { id: "pli-4", itemType: "Spot Ink", description: "Pantone 072C Reflex Blue Match", quantity: 20, unit: "Kg", rate: 720, amount: 14400 },
    ],
    subtotal: 110400,
    gstAmount: 19872,
    grandTotal: 130272,
    terms: "1. Original batch test certificate with each drum.\n2. Delivery at Perfect Printers Miraj plant.",
    status: "Ordered",
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: "qt-1",
    quoteNumber: "QT-2026-0521",
    customerId: "cust-1",
    customerName: "Cipla Healthcare Ltd.",
    contactPerson: "Dr. Arvind Shinde",
    quoteDate: "15 Aug 2026",
    validUntil: "30 Aug 2026",
    gstRate: 18,
    lineItems: [
      {
        id: "qli-1",
        jobContext: "Paracetamol 500mg Drip-Off Mono Carton",
        specs: 'Size: 115x45x35 mm | 300 GSM Cyber XL Pac FBB | 5 Colors (CMYK+072C) | Drip-Off UV | Die Cut & Side Pasted',
        quantity: 50000,
        unit: "Cartons",
        rate: 2.35,
        amount: 117500,
      },
      {
        id: "qli-2",
        jobContext: "Paracetamol 650mg Blister Outer Carton",
        specs: 'Size: 130x55x40 mm | 300 GSM FBB | 4 Colors CMYK | Gloss Aqueous Coating | Auto Lock Pasted',
        quantity: 30000,
        unit: "Cartons",
        rate: 2.65,
        amount: 79500,
      },
    ],
    subtotal: 197000,
    gstAmount: 35460,
    grandTotal: 232460,
    terms: "1. 50% Advance with Purchase Order, balance against dispatch.\n2. Plate & Die charges included for run > 50k pcs.\n3. Delivery within 7-8 working days from digital PDF artwork approval.",
    status: "Accepted",
  },
  {
    id: "qt-2",
    quoteNumber: "QT-2026-0520",
    customerId: "cust-4",
    customerName: "Zydus Natural Formulations",
    contactPerson: "Sneha Kulkarni",
    quoteDate: "12 Aug 2026",
    validUntil: "27 Aug 2026",
    gstRate: 18,
    lineItems: [
      {
        id: "qli-3",
        jobContext: "Ayurvedic Hair Vitalizer Met-Pet Box",
        specs: '320 GSM Met-Pet Gold Board | White Opaque + 4 Colors CMYK | Spot UV Drip-Off | Window Punch & Pasted',
        quantity: 30000,
        unit: "Cartons",
        rate: 4.85,
        amount: 145500,
      },
    ],
    subtotal: 145500,
    gstAmount: 26190,
    grandTotal: 171690,
    terms: "1. Strict color matching to approved Met-Pet target.\n2. 30 Days credit terms upon delivery verification.",
    status: "Sent",
  },
];

export const INITIAL_EXPENSES: MonthlyExpenses = {
  monthYear: "August 2026",
  electricity: 85400,
  salaries: 245000,
  rentAndFactory: 65000,
  maintenanceAndConsumables: 38000,
  otherExpenses: 22500,
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  { id: "notif-1", title: "Job Advance: ORD-0842", message: "Cipla Paracetamol 50k cartons moved to Press (Heidelberg CD 102).", timestamp: "10 mins ago", type: "info", isRead: false, orderId: "ORD-2026-0842" },
  { id: "notif-2", title: "Low Stock Warning", message: "Thermal Gloss BOPP Film is at 18 rolls (Reorder threshold 5 rolls).", timestamp: "1 hour ago", type: "warning", isRead: false },
  { id: "notif-3", title: "PO Approved", message: "PO-2026-0312 for ITC FBB Board ₹5,35,130 has been approved.", timestamp: "3 hours ago", type: "success", isRead: true },
  { id: "notif-4", title: "Dispatch Clearance Needed", message: "ORD-2026-0841 Green Tea 25k is ready for Delivery Challan generation.", timestamp: "5 hours ago", type: "alert", isRead: false, orderId: "ORD-2026-0841" },
];

export const INITIAL_AUDIT_LOGS: ProductionAuditLog[] = [
  { id: "log-1", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Pending", timestamp: "16 Aug 2026, 09:30", operator: "Admin (Om Upadhye)", action: "Order Created via Direct Entry", notes: "Target delivery 24th Aug" },
  { id: "log-2", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Pre-Press", timestamp: "16 Aug 2026, 14:10", operator: "Sunil Kadam", action: "CTP Plates Exposed & Baked (5 Colors)", notes: "Plate batch Kodak Electra XD #412" },
  { id: "log-3", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Sheet Allocation", timestamp: "17 Aug 2026, 10:00", operator: "Anand Sawant", action: "Paper Stock Allocated & Slit", sheetsConsumed: 4420, notes: "4,420 sheets of 300 GSM Cyber XL Pac issued" },
  { id: "log-4", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Press", timestamp: "17 Aug 2026, 16:30", operator: "Ramesh Pawar", action: "Offset Press Running on Heidelberg CD 102", cartonsProduced: 28000, scrapPercentage: 1.8, notes: "Drip-off registration aligned. Running at 9,500 imp/hr." },
];
