import {
  CustomerMaster,
  JobMaster,
  EmployeeMaster,
  MachineMaster,
  ProcessMaster,
  AdminMaster,
  JobOrder,
  InventoryItem,
  StockTransaction,
  PurchaseOrder,
  Quotation,
  MonthlyExpenses,
  NotificationItem,
  ProductionAuditLog,
} from "./types";

export const INITIAL_CUSTOMERS: CustomerMaster[] = [
  {
    id: "cust-1",
    code: "D02",
    companyName: "Cipla Healthcare Ltd",
    contactPerson: "Rajesh Shinde",
    mobile: "+91 98220 11452",
    email: "orders@cipla.com",
    location: "MIDC Kupwad, Sangli, MH - 416436",
    gstin: "27AAACA1206D1ZM",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Regular", "Pharma Cartons", "High Volume"],
    isLocked: false,
  },
  {
    id: "cust-2",
    code: "D55",
    companyName: "Adiy Packaging",
    contactPerson: "Amit Deshmukh",
    mobile: "+91 98901 44520",
    email: "adiypackaging@gmail.com",
    location: "Industrial Estate, Miraj, MH - 416410",
    gstin: "27AABCA9912E1ZQ",
    isGstRegistered: true,
    creditTerms: "15 Days Credit",
    tags: ["Regular", "FMCG", "Mono Cartons"],
    isLocked: false,
  },
  {
    id: "cust-3",
    code: "D09",
    companyName: "Airavat Pack - Kraft",
    contactPerson: "Suresh Patil",
    mobile: "+91 94230 88910",
    email: "kraft@airavatpack.com",
    location: "Market Yard, Sangli, MH - 416416",
    gstin: "27AAAPA4412K1Z9",
    isGstRegistered: true,
    creditTerms: "Immediate / Advance",
    tags: ["Agro", "Kraft Board", "Heavy Substrate"],
    isLocked: false,
  },
  {
    id: "cust-4",
    code: "D07",
    companyName: "Arva Industries",
    contactPerson: "Sneha Kulkarni",
    mobile: "+91 97654 33211",
    email: "contact@arvaindustries.com",
    location: "MIDC Shirol, Kolhapur, MH - 416103",
    gstin: "27AABCA3301L1ZT",
    isGstRegistered: true,
    creditTerms: "45 Days Credit",
    tags: ["Regular", "Met-Pet", "Premium Finishing"],
    isLocked: false,
  },
  {
    id: "cust-5",
    code: "D06",
    companyName: "Classic Packaging Solutions",
    contactPerson: "Amol Chougule",
    mobile: "+91 98224 77610",
    email: "info@classicpackaging.co.in",
    location: "Vishrambag, Sangli, MH - 416415",
    gstin: "27AAGCC8819J1Z1",
    isGstRegistered: true,
    creditTerms: "Cash On Delivery",
    tags: ["Food Packaging", "Met-Pet Gold", "Crash Lock"],
    isLocked: false,
  },
  {
    id: "cust-6",
    code: "D28",
    companyName: "Ekdant Enterprises",
    contactPerson: "Ganesh Joshi",
    mobile: "+91 98221 44321",
    email: "ekdant.enterprises@rediffmail.com",
    location: "MIDC Gokul Shirgaon, Kolhapur, MH - 416234",
    gstin: "27AABCE1122F1ZK",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["FMCG", "Pharma", "Blister Cards"],
    isLocked: false,
  },
  {
    id: "cust-7",
    code: "D80",
    companyName: "Goodluck Stationers Pvt Ltd",
    contactPerson: "Prashant Kadam",
    mobile: "+91 98905 88990",
    email: "procurement@goodluckstationers.in",
    location: "Shahupuri, Kolhapur, MH - 416001",
    gstin: "27AABCG5544H1ZX",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Commercial Print", "Stationery", "Notebooks"],
    isLocked: false,
  },
  {
    id: "cust-8",
    code: "D10",
    companyName: "Indu Industries",
    contactPerson: "Mahesh Indulkar",
    mobile: "+91 94224 33112",
    email: "indu.industries@gmail.com",
    location: "MIDC Kupwad, Sangli, MH - 416436",
    gstin: "27AAACI7788M1ZY",
    isGstRegistered: true,
    creditTerms: "15 Days Credit",
    tags: ["Industrial", "Corrugated Boxes", "Cartons"],
    isLocked: false,
  },
  {
    id: "cust-9",
    code: "D25",
    companyName: "Madhav Offset Printers",
    contactPerson: "Madhavrao Dixit",
    mobile: "+91 98226 77889",
    email: "madhavoffset@gmail.com",
    location: "Gaonbhag, Sangli, MH - 416416",
    gstin: "27AABCM9988P1ZR",
    isGstRegistered: true,
    creditTerms: "Cash / Advance",
    tags: ["Job Work", "UV Coating", "CTP Services"],
    isLocked: false,
  },
  {
    id: "cust-10",
    code: "D30",
    companyName: "Patil Trading Company",
    contactPerson: "Sachin Patil",
    mobile: "+91 94220 55667",
    email: "patiltrading.miraj@gmail.com",
    location: "Gandhi Chowk, Miraj, MH - 416410",
    gstin: "27AAAFP1234K1Z0",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Agro Seeds", "Fertilizer Cartons", "Duplex"],
    isLocked: false,
  },
  {
    id: "cust-11",
    code: "D50",
    companyName: "Pavan Enterprises",
    contactPerson: "Pavan More",
    mobile: "+91 98600 22334",
    email: "pavanenterprises.sangli@gmail.com",
    location: "MIDC Miraj, Sangli, MH - 416410",
    gstin: "27AAACP4567J1Z8",
    isGstRegistered: true,
    creditTerms: "15 Days Credit",
    tags: ["Hardware Boxes", "Lamination", "Die Cut"],
    isLocked: false,
  },
  {
    id: "cust-12",
    code: "D17",
    companyName: "Pragati Packaging Udyog",
    contactPerson: "Vijay Jadhav",
    mobile: "+91 98223 99881",
    email: "pragatipackaging@yahoo.com",
    location: "Laxmi Market, Ichalkaranji, MH - 416115",
    gstin: "27AABCP6789D1Z4",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Textile Cartons", "Apparel Boxes", "Drip-off"],
    isLocked: false,
  },
  {
    id: "cust-13",
    code: "D01",
    companyName: "Quality Screens Pvt Ltd",
    contactPerson: "Anand Kulkarni",
    mobile: "+91 98900 11223",
    email: "qualityscreens@gmail.com",
    location: "Udyog Bhavan, Shivaji Nagar, Sangli, MH - 416416",
    gstin: "27AABCQ8901E1Z3",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Screen Printing", "Spot UV", "Specialty Coating"],
    isLocked: false,
  },
  {
    id: "cust-14",
    code: "D05",
    companyName: "Radha Packaging Industries",
    contactPerson: "Rameshwar Sarda",
    mobile: "+91 94221 66778",
    email: "radhapackaging@gmail.com",
    location: "MIDC Shirol, Kolhapur, MH - 416103",
    gstin: "27AAACR2345B1Z7",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Pharma Foil", "Mono Cartons", "Embossed"],
    isLocked: false,
  },
  {
    id: "cust-15",
    code: "D19",
    companyName: "Shagun Packaging",
    contactPerson: "Nitin Oswal",
    mobile: "+91 98228 33445",
    email: "shagunpackaging@hotmail.com",
    location: "Market Yard, Miraj, MH - 416410",
    gstin: "27AABCS3456N1Z6",
    isGstRegistered: true,
    creditTerms: "Immediate / Advance",
    tags: ["Sweet Boxes", "Gold Stamping", "Food Grade"],
    isLocked: false,
  },
  {
    id: "cust-16",
    code: "D49",
    companyName: "Shree Varad Industries",
    contactPerson: "Varadraj Mane",
    mobile: "+91 97640 44556",
    email: "varadindustries@gmail.com",
    location: "MIDC Kupwad, Sangli, MH - 416436",
    gstin: "27AAACS4567M1Z5",
    isGstRegistered: true,
    creditTerms: "45 Days Credit",
    tags: ["Heavy Duty Corrugation", "Fluted Cartons"],
    isLocked: false,
  },
  {
    id: "cust-17",
    code: "D08",
    companyName: "Srisanved Aadimaya Industries Pvt Ltd",
    contactPerson: "Siddharth Sawant",
    mobile: "+91 98225 11990",
    email: "procurement@srisanved.com",
    location: "Five Star MIDC Kagal, Kolhapur, MH - 416236",
    gstin: "27AABCS7890C1Z2",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["High Volume Pharma", "Export Cartons", "Met-Pet"],
    isLocked: false,
  },
  {
    id: "cust-18",
    code: "D20",
    companyName: "Swastik Offset",
    contactPerson: "Sunil Shinde",
    mobile: "+91 98902 33110",
    email: "swastikoffset@gmail.com",
    location: "Khanbhag, Sangli, MH - 416416",
    gstin: "27AAACS8901K1Z1",
    isGstRegistered: true,
    creditTerms: "15 Days Credit",
    tags: ["Offset Printing", "Leaflets", "Brochures"],
    isLocked: false,
  },
  {
    id: "cust-19",
    code: "D21",
    companyName: "Tejas Industries",
    contactPerson: "Tejas Shah",
    mobile: "+91 94232 77889",
    email: "tejasindustries.sangli@gmail.com",
    location: "MIDC Miraj, Sangli, MH - 416410",
    gstin: "27AAACT9012F1Z0",
    isGstRegistered: true,
    creditTerms: "30 Days Credit",
    tags: ["Consumer Goods", "Duplex Board Cartons"],
    isLocked: false,
  },
  {
    id: "cust-20",
    code: "D52",
    companyName: "Tushant Packaging",
    contactPerson: "Tushar Bhosale",
    mobile: "+91 98229 55664",
    email: "tushantpackaging@gmail.com",
    location: "MIDC Kupwad, Sangli, MH - 416436",
    gstin: "27AABCT0123L1Z9",
    isGstRegistered: true,
    creditTerms: "15 Days Credit",
    tags: ["Folding Boxes", "Window Patching"],
    isLocked: false,
  },
  {
    id: "cust-21",
    code: "D22",
    companyName: "Yashwant Industrial Works Pvt Ltd",
    contactPerson: "Yashwantrao Thorat",
    mobile: "+91 98220 88776",
    email: "info@yashwantworks.com",
    location: "MIDC Gokul Shirgaon, Kolhapur, MH - 416234",
    gstin: "27AAACY1234P1Z8",
    isGstRegistered: true,
    creditTerms: "45 Days Credit",
    tags: ["Auto Components Packaging", "Heavy Corrugation", "Rigid"],
    isLocked: false,
  },
];

export const INITIAL_JOBS: JobMaster[] = [
  {
    id: "job-1",
    jobCode: "JC-MED-5001",
    productName: "Paracetamol 500mg Embossed Drip-off Mono Carton",
    customerId: "cust-1",
    customerCode: "D02",
    customerName: "Cipla Healthcare Ltd",
    sheetSize: '28" × 40" (710 × 1020 mm)',
    sheetLengthInches: 40,
    sheetWidthInches: 28,
    boardType: "FBB Cyber XL Pac",
    boardGsm: 300,
    colors: "CMYK + Pantone 072C Reflex Blue + Spot Drip-off",
    numColors: 5,
    sides: 1,
    ups: 12,
    dieCode: "DIE-MED-042",
    artworkUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Thermal Gloss Lamination", "Spot UV Drip-off", "Die Punching", "Straight Line Pasting"],
  },
  {
    id: "job-2",
    jobCode: "JC-FMCG-2004",
    productName: "Organic Green Tea 25s Lock Bottom Carton",
    customerId: "cust-2",
    customerCode: "D55",
    customerName: "Adiy Packaging",
    sheetSize: '25" × 36" (635 × 915 mm)',
    sheetLengthInches: 36,
    sheetWidthInches: 25,
    boardType: "Virgin Kraft Backed Ivory Board",
    boardGsm: 280,
    colors: "CMYK + Eco Matte Aqueous Varnish",
    numColors: 4,
    sides: 1,
    ups: 8,
    dieCode: "DIE-FMCG-018",
    artworkUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Aqueous Matte Coating", "Die Punching & Embossing", "Crash Lock Bottom Pasting"],
  },
  {
    id: "job-3",
    jobCode: "JC-AGRO-7011",
    productName: "Bio-Fertilizer 1kg Heavy Duty Corrugated Laminated Mono Box",
    customerId: "cust-3",
    customerCode: "D09",
    customerName: "Airavat Pack - Kraft",
    sheetSize: '30" × 40" (760 × 1020 mm)',
    sheetLengthInches: 40,
    sheetWidthInches: 30,
    boardType: "Duplex Grey Back Coated",
    boardGsm: 350,
    colors: "CMYK + High Gloss UV Varnish",
    numColors: 4,
    sides: 1,
    ups: 6,
    dieCode: "DIE-AGRO-091",
    artworkUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Thermal Gloss Lamination", "Die Punching", "Heavy Flute Pasting"],
  },
  {
    id: "job-4",
    jobCode: "JC-MET-8802",
    productName: "Ayurvedic Hair Vitalizer Met-Pet Gold Foil Drip-Off Box",
    customerId: "cust-4",
    customerCode: "D07",
    customerName: "Arva Industries",
    sheetSize: '22" × 32" (560 × 810 mm)',
    sheetLengthInches: 32,
    sheetWidthInches: 22,
    boardType: "Met-Pet Gold Polyester Laminated FBB",
    boardGsm: 320,
    colors: "White Base + CMYK + Spot Gloss UV Drip-off",
    numColors: 6,
    sides: 1,
    ups: 10,
    dieCode: "DIE-LUX-033",
    artworkUrl: "https://images.unsplash.com/photo-1608248597359-0091398bb9ff?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["UV Inks Curing", "Drip-off Texture", "Precision Die Cut", "Side Seam Pasting"],
  },
  {
    id: "job-5",
    jobCode: "JC-SWEET-302",
    productName: "Premium Kaju Katli 500g Golden Rigid Style Folding Box",
    customerId: "cust-5",
    customerCode: "D06",
    customerName: "Classic Packaging Solutions",
    sheetSize: '28" × 40" (710 × 1020 mm)',
    sheetLengthInches: 40,
    sheetWidthInches: 28,
    boardType: "Food Grade SBS Virgin Board",
    boardGsm: 350,
    colors: "CMYK + Gold Foil Stamping + Velvet Soft Touch Lamination",
    numColors: 5,
    sides: 2,
    ups: 4,
    dieCode: "DIE-SWT-104",
    artworkUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Velvet Soft-Touch Lamination", "Hot Foil Stamping", "Embossing", "Die Punching", "Manual Box Assembly"],
  },
  {
    id: "job-6",
    jobCode: "JC-PHARMA-104",
    productName: "Cough Syrup 100ml Embossed Inner Carton",
    customerId: "cust-6",
    customerCode: "D28",
    customerName: "Ekdant Enterprises",
    sheetSize: '25" × 36" (635 × 915 mm)',
    sheetLengthInches: 36,
    sheetWidthInches: 25,
    boardType: "FBB Cyber XL Pac",
    boardGsm: 280,
    colors: "CMYK + Pantone 485C Red",
    numColors: 5,
    sides: 1,
    ups: 16,
    dieCode: "DIE-MED-099",
    artworkUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    postPressProcesses: ["Thermal Gloss Lamination", "Die Punching", "Straight Line Pasting"],
  },
];

export const INITIAL_EMPLOYEES: EmployeeMaster[] = [
  {
    id: "emp-1",
    staffId: "EMP-101",
    name: "Mr. Basavraj Khemalapure",
    phone: "9011148816",
    bloodGroup: "O+",
    email: "basavrajkhemalapure@gmail.com",
    department: "Sheet Allocation",
    shift: "Morning (8AM-4PM)",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-2",
    staffId: "EMP-102",
    name: "Mr. Chandrakant Kalinge",
    phone: "7744070284",
    bloodGroup: "O+",
    email: "chandrakantkalinge0101@gmail.com",
    department: "Dispatch",
    shift: "General",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-3",
    staffId: "EMP-103",
    name: "Mr. Dhanappa Araballi",
    phone: "9049297399",
    bloodGroup: "B+",
    email: "dmaraballi75@gmail.com",
    department: "Accounts",
    shift: "General",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-4",
    staffId: "EMP-104",
    name: "Mr. Janardan Suryavanshi",
    phone: "8983180562",
    bloodGroup: "A+",
    email: "janardhanms885@gmail.com",
    department: "Post-Press",
    shift: "Evening (4PM-12AM)",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-5",
    staffId: "EMP-105",
    name: "Mr. Mukund Miraje",
    phone: "8830799339",
    bloodGroup: "A+",
    email: "mukund.miraj111@gmail.com",
    department: "Press",
    shift: "Morning (8AM-4PM)",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-6",
    staffId: "EMP-106",
    name: "Mr. Prasad Ponkshe",
    phone: "9850909280",
    bloodGroup: "O+",
    email: "prasadponkshe68@gmail.com",
    department: "Pre-Press",
    shift: "Morning (8AM-4PM)",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-7",
    staffId: "EMP-107",
    name: "Mr. Siddhu Lokure",
    phone: "9834383795",
    bloodGroup: "A+",
    email: "siddhulokure2@gmail.com",
    department: "Post-Press",
    shift: "Morning (8AM-4PM)",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-8",
    staffId: "EMP-108",
    name: "Mr. Vaibhav Gitaje",
    phone: "8308567553",
    bloodGroup: "O+",
    email: "vaibhav.gitaje8648@gmail.com",
    department: "Press",
    shift: "Evening (4PM-12AM)",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-9",
    staffId: "EMP-109",
    name: "Mr. Vivek Kadam",
    phone: "9975840515",
    bloodGroup: "A+",
    email: "vivekkadamvvk1991@gmail.com",
    department: "Press",
    shift: "Morning (8AM-4PM)",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-10",
    staffId: "EMP-110",
    name: "Mrs. Pournima Madke",
    phone: "9130902424",
    bloodGroup: "A+",
    email: "designs@perfectprinters.co.in",
    department: "Pre-Press",
    shift: "General",
    status: "Active",
    isLocked: false,
  },
  {
    id: "emp-11",
    staffId: "EMP-111",
    name: "Mrs. Tejashree Merekar",
    phone: "9960255454",
    bloodGroup: "AB-",
    email: "wandarets@gmail.com",
    department: "Accounts",
    shift: "General",
    status: "Active",
    isLocked: false,
  },
];

export const INITIAL_MACHINES: MachineMaster[] = [
  {
    id: "mac-1",
    machineId: "M-01",
    name: "Heidelberg Speedmaster CD 102 (5-Color + Coater)",
    description: "Printing - 28 x 40 - 5 Color + Coater",
    department: "Press",
    type: "Offset Press",
    speedImpPerHour: 12000,
    hourlyRate: 2200,
    currentJobCode: "JC-MED-5001",
    status: "Running",
  },
  {
    id: "mac-2",
    machineId: "M-02",
    name: "Komori L540",
    description: "Printing - 28 x 40 - 5 Color",
    department: "Press",
    type: "Offset Press",
    speedImpPerHour: 10000,
    hourlyRate: 1800,
    currentJobCode: "JC-FMCG-2004",
    status: "Running",
  },
  {
    id: "mac-3",
    machineId: "M-03",
    name: 'Lamination A - 38"',
    description: '38" BOPP Lamination - Wet',
    department: "Post-Press",
    type: "Laminator",
    speedImpPerHour: 5000,
    hourlyRate: 850,
    currentJobCode: "JC-AGRO-7011",
    status: "Running",
  },
  {
    id: "mac-4",
    machineId: "M-04",
    name: 'Lamination B - 42"',
    description: "BOPP Lamination - Wet",
    department: "Post-Press",
    type: "Laminator",
    speedImpPerHour: 6000,
    hourlyRate: 950,
    currentJobCode: "JC-MET-8802",
    status: "Running",
  },
];

export const INITIAL_PROCESSES: ProcessMaster[] = [
  { id: "prc-1", code: "P-CTP", name: "Thermal CTP Plate Exposure & Baking", unitRate: 450, rateUnit: "per Plate", category: "Pre-Press", machineType: "CTP Processor", setupTimeMin: 15 },
  { id: "prc-2", code: "P-OFF", name: "Offset 4-Color Printing Impression", unitRate: 180, rateUnit: "per 1000 Imp", category: "Press", machineType: "Offset Press", setupTimeMin: 30 },
  { id: "prc-3", code: "P-LAM-T", name: "Thermal Gloss / Matte BOPP Lamination", unitRate: 1.40, rateUnit: "per Sheet", category: "Coating & Lamination", machineType: "Laminator", setupTimeMin: 20 },
  { id: "prc-4", code: "P-UV-DRIP", name: "Inline UV Drip-off Structure Coating", unitRate: 2.20, rateUnit: "per Sheet", category: "Coating & Lamination", machineType: "Coater", setupTimeMin: 25 },
  { id: "prc-5", code: "P-DIE", name: "Automatic Die Punching & Creasing", unitRate: 0.95, rateUnit: "per Sheet", category: "Finishing & Pasting", machineType: "Die Cutter", setupTimeMin: 40 },
  { id: "prc-6", code: "P-PASTE-L", name: "Linear Side-Seam Auto Pasting", unitRate: 0.22, rateUnit: "per Carton", category: "Finishing & Pasting", machineType: "Folder Gluer", setupTimeMin: 25 },
  { id: "prc-7", code: "P-PASTE-CR", name: "Crash Lock Bottom Auto Pasting", unitRate: 0.45, rateUnit: "per Carton", category: "Finishing & Pasting", machineType: "Folder Gluer", setupTimeMin: 45 },
];

export const INITIAL_ADMINS: AdminMaster[] = [
  { id: "adm-1", username: "admin_om", name: "Om Upadhye", email: "om@perfectprinters.com", role: "ADMIN", status: "Active", lastLogin: "Today, 19:42" },
  { id: "adm-2", username: "sales_mahesh", name: "Mahesh Joshi", email: "mahesh@perfectprinters.com", role: "SALES", status: "Active", lastLogin: "Today, 17:15" },
  { id: "adm-3", username: "prod_sawant", name: "Anand Sawant", email: "anand@perfectprinters.com", role: "PRODUCTION", status: "Active", lastLogin: "Today, 18:30" },
  { id: "adm-4", username: "acc_shinde", name: "Ketan Shinde", email: "accounts@perfectprinters.com", role: "ACCOUNTS", status: "Active", lastLogin: "Yesterday, 16:50" },
];

export const INITIAL_JOB_ORDERS: JobOrder[] = [
  {
    id: "ORD-2026-0842",
    jobId: "job-1",
    jobCode: "JC-MED-5001",
    jobName: "Paracetamol 500mg Embossed Drip-off Mono Carton",
    customerId: "cust-1",
    customerName: "Cipla Healthcare Ltd",
    customerCode: "D02",
    quantity: 50000,
    ups: 12,
    totalSheetsRequired: 4420,
    makereadySheets: 250,
    sheetSize: '28" × 40"',
    boardType: "FBB Cyber XL Pac",
    boardGsm: 300,
    colors: "CMYK + Pantone 072C",
    numColors: 5,
    status: "Press",
    progressPercent: 60,
    orderDate: "16 Aug 2026",
    dueDate: "24 Aug 2026",
    instructions: "High gloss drip-off texture required on client logo. Strict cleanroom packaging.",
    artworkUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600&auto=format&fit=crop",
    assignedMachine: "Heidelberg CD 102",
    assignedOperator: "Ramesh Pawar",
  },
  {
    id: "ORD-2026-0841",
    jobId: "job-2",
    jobCode: "JC-FMCG-2004",
    jobName: "Organic Green Tea 25s Lock Bottom Carton",
    customerId: "cust-2",
    customerName: "Adiy Packaging",
    customerCode: "D55",
    quantity: 25000,
    ups: 8,
    totalSheetsRequired: 3325,
    makereadySheets: 200,
    sheetSize: '25" × 36"',
    boardType: "Virgin Kraft Backed Ivory Board",
    boardGsm: 280,
    colors: "CMYK + Aqueous Matte",
    numColors: 4,
    status: "Post-Press",
    progressPercent: 80,
    orderDate: "14 Aug 2026",
    dueDate: "22 Aug 2026",
    instructions: "Crash lock bottom test report needed before palletization.",
    artworkUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=600&auto=format&fit=crop",
    assignedMachine: "DGM Smartfold Gluer",
    assignedOperator: "Santosh Mane",
  },
  {
    id: "ORD-2026-0840",
    jobId: "job-3",
    jobCode: "JC-AGRO-7011",
    jobName: "Bio-Fertilizer 1kg Heavy Duty Outer Box",
    customerId: "cust-3",
    customerName: "Airavat Pack - Kraft",
    customerCode: "D09",
    quantity: 15000,
    ups: 6,
    totalSheetsRequired: 2650,
    makereadySheets: 150,
    sheetSize: '30" × 40"',
    boardType: "Duplex Grey Back Coated",
    boardGsm: 350,
    colors: "CMYK + High Gloss UV",
    numColors: 4,
    status: "Sheet Allocation",
    progressPercent: 40,
    orderDate: "18 Aug 2026",
    dueDate: "28 Aug 2026",
    instructions: "Verify moisture content of 350 GSM board before cutting.",
    artworkUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "ORD-2026-0839",
    jobId: "job-4",
    jobCode: "JC-MET-8802",
    jobName: "Ayurvedic Hair Vitalizer Met-Pet Gold Foil Drip-Off Box",
    customerId: "cust-4",
    customerName: "Arva Industries",
    customerCode: "D07",
    quantity: 30000,
    ups: 10,
    totalSheetsRequired: 3250,
    makereadySheets: 250,
    sheetSize: '22" × 32"',
    boardType: "Met-Pet Gold Polyester Laminated FBB",
    boardGsm: 320,
    colors: "White Base + CMYK + Drip-off",
    numColors: 6,
    status: "Pre-Press",
    progressPercent: 25,
    orderDate: "19 Aug 2026",
    dueDate: "30 Aug 2026",
    instructions: "Customer color proof approved via email on 18th Aug.",
    artworkUrl: "https://images.unsplash.com/photo-1608248597359-0091398bb9ff?q=80&w=600&auto=format&fit=crop",
    assignedMachine: "Screen PlateRite CTP",
    assignedOperator: "Sunil Kadam",
  },
  {
    id: "ORD-2026-0838",
    jobId: "job-5",
    jobCode: "JC-SWEET-302",
    jobName: "Premium Kaju Katli 500g Golden Rigid Folding Box",
    customerId: "cust-5",
    customerName: "Classic Packaging Solutions",
    customerCode: "D06",
    quantity: 10000,
    ups: 4,
    totalSheetsRequired: 2650,
    makereadySheets: 150,
    sheetSize: '28" × 40"',
    boardType: "Food Grade SBS Virgin Board",
    boardGsm: 350,
    colors: "CMYK + Gold Foil",
    numColors: 5,
    status: "Pending",
    progressPercent: 10,
    orderDate: "19 Aug 2026",
    dueDate: "02 Sep 2026",
    instructions: "Awaiting board delivery from ITC Bhadrachalam dealer.",
    artworkUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "ORD-2026-0835",
    jobId: "job-1",
    jobCode: "JC-MED-5001",
    jobName: "Paracetamol 500mg (Batch July Export)",
    customerId: "cust-1",
    customerName: "Aarvi Packaging",
    customerCode: "D02",
    quantity: 100000,
    ups: 12,
    totalSheetsRequired: 8600,
    makereadySheets: 260,
    sheetSize: '28" × 40"',
    boardType: "FBB Cyber XL Pac",
    boardGsm: 300,
    colors: "CMYK + Spot Blue",
    numColors: 5,
    status: "Completed",
    progressPercent: 100,
    orderDate: "02 Aug 2026",
    dueDate: "12 Aug 2026",
    dispatchDate: "11 Aug 2026",
    challanNo: "DC-2026-0418",
    invoiceNo: "INV-2026-1190",
  },
  {
    id: "ORD-2026-0834",
    jobId: "job-2",
    jobCode: "JC-FMCG-2004",
    jobName: "Organic Green Tea (Monsoon Packaging)",
    customerId: "cust-2",
    customerName: "Adiy Packaging",
    customerCode: "D55",
    quantity: 40000,
    ups: 8,
    totalSheetsRequired: 5200,
    makereadySheets: 200,
    sheetSize: '25" × 36"',
    boardType: "Virgin Kraft Backed Ivory Board",
    boardGsm: 280,
    colors: "CMYK + Aqueous Matte",
    numColors: 4,
    status: "Completed",
    progressPercent: 100,
    orderDate: "28 Jul 2026",
    dueDate: "08 Aug 2026",
    dispatchDate: "07 Aug 2026",
    challanNo: "DC-2026-0410",
    invoiceNo: "INV-2026-1175",
  },
  {
    id: "ORD-2026-0830",
    jobId: "job-3",
    jobCode: "JC-AGRO-7011",
    jobName: "Bio-Fertilizer 1kg Carton (Spec Rev C)",
    customerId: "cust-3",
    customerName: "Airavat Pack - Kraft",
    customerCode: "D09",
    quantity: 20000,
    ups: 6,
    totalSheetsRequired: 3500,
    makereadySheets: 160,
    sheetSize: '30" × 40"',
    boardType: "Duplex Grey Back Coated",
    boardGsm: 350,
    colors: "CMYK",
    numColors: 4,
    status: "On Hold",
    progressPercent: 40,
    orderDate: "05 Aug 2026",
    dueDate: "20 Aug 2026",
    holdReason: "Client requested barcode & ingredient artwork correction on front panel.",
  },
  {
    id: "ORD-2026-0828",
    jobId: "job-4",
    jobCode: "JC-MET-8802",
    jobName: "Ayurvedic Hair Vitalizer (Test Batch)",
    customerId: "cust-4",
    customerName: "Arva Industries",
    customerCode: "D07",
    quantity: 5000,
    ups: 10,
    totalSheetsRequired: 700,
    makereadySheets: 200,
    sheetSize: '22" × 32"',
    boardType: "Met-Pet Gold",
    boardGsm: 320,
    colors: "White + CMYK",
    numColors: 5,
    status: "Cancelled",
    progressPercent: 10,
    orderDate: "20 Jul 2026",
    dueDate: "30 Jul 2026",
    cancelReason: "Client changed formulation bottle size; revised die punch needed.",
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: "inv-1", sku: "BRD-FBB-300", name: "ITC Cyber XL Pac FBB 300 GSM (28x40 in)", category: "Paper & Board", stockType: "Own Stock", quantity: 18500, unit: "Sheets", reorderLevel: 5000, costPerUnit: 18.5, totalValue: 342250, location: "Bay A - Stack 12", lastUpdated: "18 Aug 2026" },
  { id: "inv-2", sku: "BRD-DUP-350", name: "Emami Super White Duplex Grey Back 350 GSM (30x40 in)", category: "Paper & Board", stockType: "Own Stock", quantity: 9200, unit: "Sheets", reorderLevel: 3000, costPerUnit: 22.0, totalValue: 202400, location: "Bay A - Stack 05", lastUpdated: "17 Aug 2026" },
  { id: "inv-3", sku: "BRD-MET-320", name: "Met-Pet Gold Laminated FBB Board 320 GSM (22x32 in)", category: "Paper & Board", stockType: "Client Stock", clientName: "Arva Industries", quantity: 4500, unit: "Sheets", reorderLevel: 1000, costPerUnit: 29.5, totalValue: 132750, location: "Bay C - Client Staging", lastUpdated: "19 Aug 2026" },
  { id: "inv-4", sku: "INK-CMYK-SET", name: "Hubergroup Premium Sheetfed Offset Ink Set (CMYK)", category: "Inks & Varnishes", stockType: "Own Stock", quantity: 240, unit: "Kg", reorderLevel: 50, costPerUnit: 480, totalValue: 115200, location: "Ink Room - Cabinet 1", lastUpdated: "16 Aug 2026" },
  { id: "inv-5", sku: "INK-PAN-072C", name: "Pantone 072C Reflex Blue Spot Ink", category: "Inks & Varnishes", stockType: "Own Stock", quantity: 35, unit: "Kg", reorderLevel: 10, costPerUnit: 720, totalValue: 25200, location: "Ink Room - Special", lastUpdated: "15 Aug 2026" },
  { id: "inv-6", sku: "FILM-BOPP-15U", name: "Thermal Gloss BOPP Film 15 Micron (710mm Roll)", category: "Lamination Film", stockType: "Own Stock", quantity: 18, unit: "Rolls", reorderLevel: 5, costPerUnit: 3400, totalValue: 61200, location: "Lamination Store", lastUpdated: "12 Aug 2026" },
  { id: "inv-7", sku: "ADH-PAST-WTR", name: "Pidilite Fast Setting Side Seam Adhesive", category: "Adhesives & Gum", stockType: "Own Stock", quantity: 420, unit: "Kg", reorderLevel: 100, costPerUnit: 145, totalValue: 60900, location: "Chemical Store", lastUpdated: "14 Aug 2026" },
  { id: "inv-8", sku: "COAT-UV-DRIP", name: "Hi-Tech UV Drip-off Gloss Varnish & Primer Kit", category: "UV & Aqueous Coatings", stockType: "Own Stock", quantity: 85, unit: "Kg", reorderLevel: 25, costPerUnit: 680, totalValue: 57800, location: "UV Mixing Room", lastUpdated: "17 Aug 2026" },
  { id: "inv-9", sku: "PLT-CTP-THERM", name: "Kodak Electra XD Thermal CTP Plates (770x1030 mm)", category: "Chemicals & Plates", stockType: "Own Stock", quantity: 140, unit: "Plates", reorderLevel: 40, costPerUnit: 380, totalValue: 53200, location: "CTP Dark Room", lastUpdated: "19 Aug 2026" },
];

export const INITIAL_TRANSACTIONS: StockTransaction[] = [
  { id: "tx-1", itemId: "inv-1", sku: "BRD-FBB-300", itemName: "ITC Cyber XL Pac FBB 300 GSM", type: "Stock In", quantity: 10000, unit: "Sheets", date: "16 Aug 2026", referenceNo: "PO-2026-0308", authorizedBy: "Om Upadhye", notes: "GRN-2026-091 verified from ITC dealer" },
  { id: "tx-2", itemId: "inv-1", sku: "BRD-FBB-300", itemName: "ITC Cyber XL Pac FBB 300 GSM", type: "Material Out (Job Issuance)", quantity: 4420, unit: "Sheets", date: "16 Aug 2026", referenceNo: "ORD-2026-0842", jobCode: "JC-MED-5001", authorizedBy: "Anand Sawant", notes: "Issued for Cipla Paracetamol 50k run" },
  { id: "tx-3", itemId: "inv-4", sku: "INK-CMYK-SET", itemName: "Hubergroup Offset CMYK Inks", type: "Material Out (Job Issuance)", quantity: 35, unit: "Kg", date: "17 Aug 2026", referenceNo: "ORD-2026-0842", jobCode: "JC-MED-5001", authorizedBy: "Ramesh Pawar" },
  { id: "tx-4", itemId: "inv-8", sku: "COAT-UV-DRIP", itemName: "UV Drip-off Gloss Varnish Kit", type: "Material Out (Job Issuance)", quantity: 15, unit: "Kg", date: "17 Aug 2026", referenceNo: "ORD-2026-0842", jobCode: "JC-MED-5001", authorizedBy: "Ramesh Pawar" },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-1",
    poNumber: "PO-2026-0312",
    supplierName: "Paper Trade Corporation (ITC Authorized)",
    supplierGstin: "27AAACP9910D1ZL",
    supplierAddress: "Industrial Area, Kolhapur, MH - 416001",
    poDate: "18 Aug 2026",
    deliveryDate: "23 Aug 2026",
    gstRate: 18,
    lineItems: [
      { id: "pli-1", itemType: "FBB Paperboard", description: "ITC Cyber XL Pac 300 GSM 28x40 inches", quantity: 15000, unit: "Sheets", rate: 18.50, amount: 277500 },
      { id: "pli-2", itemType: "Duplex Board", description: "Emami Super White Duplex 350 GSM 30x40 inches", quantity: 8000, unit: "Sheets", rate: 22.00, amount: 176000 },
    ],
    subtotal: 453500,
    gstAmount: 81630,
    grandTotal: 535130,
    terms: "1. 30 Days credit from date of invoice.\n2. Moisture content must be within 6-7%.\n3. Defective sheets subject to immediate debit note.",
    status: "Approved",
  },
  {
    id: "po-2",
    poNumber: "PO-2026-0311",
    supplierName: "Hubergroup India Private Limited",
    supplierGstin: "27AAACH0112F1ZK",
    supplierAddress: "Rabale MIDC, Navi Mumbai, MH - 400701",
    poDate: "15 Aug 2026",
    deliveryDate: "20 Aug 2026",
    gstRate: 18,
    lineItems: [
      { id: "pli-3", itemType: "Offset Inks", description: "Process Cyan, Magenta, Yellow, Black (50kg each)", quantity: 200, unit: "Kg", rate: 480, amount: 96000 },
      { id: "pli-4", itemType: "Spot Ink", description: "Pantone 072C Reflex Blue Match", quantity: 20, unit: "Kg", rate: 720, amount: 14400 },
    ],
    subtotal: 110400,
    gstAmount: 19872,
    grandTotal: 130272,
    terms: "1. Original batch test certificate with each drum.\n2. Delivery at Perfect Printers Miraj plant.",
    status: "Ordered",
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: "qt-1",
    quoteNumber: "QT-2026-0521",
    customerId: "cust-1",
    customerName: "Aarvi Packaging",
    contactPerson: "Rajesh Shinde",
    quoteDate: "15 Aug 2026",
    validUntil: "30 Aug 2026",
    gstRate: 18,
    lineItems: [
      {
        id: "qli-1",
        jobContext: "Paracetamol 500mg Drip-Off Mono Carton",
        specs: 'Size: 115x45x35 mm | 300 GSM Cyber XL Pac FBB | 5 Colors (CMYK+072C) | Drip-Off UV | Die Cut & Side Pasted',
        quantity: 50000,
        unit: "Cartons",
        rate: 2.35,
        amount: 117500,
      },
      {
        id: "qli-2",
        jobContext: "Paracetamol 650mg Blister Outer Carton",
        specs: 'Size: 130x55x40 mm | 300 GSM FBB | 4 Colors CMYK | Gloss Aqueous Coating | Auto Lock Pasted',
        quantity: 30000,
        unit: "Cartons",
        rate: 2.65,
        amount: 79500,
      },
    ],
    subtotal: 197000,
    gstAmount: 35460,
    grandTotal: 232460,
    terms: "1. 50% Advance with Purchase Order, balance against dispatch.\n2. Plate & Die charges included for run > 50k pcs.\n3. Delivery within 7-8 working days from digital PDF artwork approval.",
    status: "Accepted",
  },
  {
    id: "qt-2",
    quoteNumber: "QT-2026-0520",
    customerId: "cust-4",
    customerName: "Arva Industries",
    contactPerson: "Sneha Kulkarni",
    quoteDate: "12 Aug 2026",
    validUntil: "27 Aug 2026",
    gstRate: 18,
    lineItems: [
      {
        id: "qli-3",
        jobContext: "Ayurvedic Hair Vitalizer Met-Pet Box",
        specs: '320 GSM Met-Pet Gold Board | White Opaque + 4 Colors CMYK | Spot UV Drip-Off | Window Punch & Pasted',
        quantity: 30000,
        unit: "Cartons",
        rate: 4.85,
        amount: 145500,
      },
    ],
    subtotal: 145500,
    gstAmount: 26190,
    grandTotal: 171690,
    terms: "1. Strict color matching to approved Met-Pet target.\n2. 30 Days credit terms upon delivery verification.",
    status: "Sent",
  },
];

export const INITIAL_EXPENSES: MonthlyExpenses = {
  monthYear: "August 2026",
  electricity: 85400,
  salaries: 245000,
  rentAndFactory: 65000,
  maintenanceAndConsumables: 38000,
  otherExpenses: 22500,
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  { id: "notif-1", title: "Job Advance: ORD-0842", message: "Cipla Paracetamol 50k cartons moved to Press (Heidelberg CD 102).", timestamp: "10 mins ago", type: "info", isRead: false, orderId: "ORD-2026-0842" },
  { id: "notif-2", title: "Low Stock Warning", message: "Thermal Gloss BOPP Film is at 18 rolls (Reorder threshold 5 rolls).", timestamp: "1 hour ago", type: "warning", isRead: false },
  { id: "notif-3", title: "PO Approved", message: "PO-2026-0312 for ITC FBB Board ₹5,35,130 has been approved.", timestamp: "3 hours ago", type: "success", isRead: true },
  { id: "notif-4", title: "Dispatch Clearance Needed", message: "ORD-2026-0841 Green Tea 25k is ready for Delivery Challan generation.", timestamp: "5 hours ago", type: "alert", isRead: false, orderId: "ORD-2026-0841" },
];

export const INITIAL_AUDIT_LOGS: ProductionAuditLog[] = [
  { id: "log-1", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Pending", timestamp: "16 Aug 2026, 09:30", operator: "Admin (Om Upadhye)", action: "Order Created via Direct Entry", notes: "Target delivery 24th Aug" },
  { id: "log-2", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Pre-Press", timestamp: "16 Aug 2026, 14:10", operator: "Sunil Kadam", action: "CTP Plates Exposed & Baked (5 Colors)", notes: "Plate batch Kodak Electra XD #412" },
  { id: "log-3", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Sheet Allocation", timestamp: "17 Aug 2026, 10:00", operator: "Anand Sawant", action: "Paper Stock Allocated & Slit", sheetsConsumed: 4420, notes: "4,420 sheets of 300 GSM Cyber XL Pac issued" },
  { id: "log-4", orderId: "ORD-2026-0842", jobCode: "JC-MED-5001", stage: "Press", timestamp: "17 Aug 2026, 16:30", operator: "Ramesh Pawar", action: "Offset Press Running on Heidelberg CD 102", cartonsProduced: 28000, scrapPercentage: 1.8, notes: "Drip-off registration aligned. Running at 9,500 imp/hr." },
];
